/*
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, you can obtain one at https://mozilla.org/MPL/2.0/.
 *
 * Copyright Oxide Computer Company
 */

export type Icon =
  | { name: 'access'; size: 16 }
  | { name: 'access'; size: 24 }
  | { name: 'access-token'; size: 16 }
  | { name: 'access-token'; size: 24 }
  | { name: 'action'; size: 16 }
  | { name: 'action'; size: 24 }
  | { name: 'add'; size: 12 }
  | { name: 'add-roundel'; size: 12 }
  | { name: 'add-roundel'; size: 16 }
  | { name: 'add-roundel'; size: 24 }
  | { name: 'affinity'; size: 16 }
  | { name: 'affinity'; size: 24 }
  | { name: 'auto-restart'; size: 12 }
  | { name: 'calendar'; size: 16 }
  | { name: 'calendar'; size: 24 }
  | { name: 'carat-down'; size: 12 }
  | { name: 'carat-left'; size: 12 }
  | { name: 'carat-right'; size: 12 }
  | { name: 'carat-up'; size: 12 }
  | { name: 'chat'; size: 16 }
  | { name: 'chat'; size: 24 }
  | { name: 'checkmark'; size: 12 }
  | { name: 'clipboard'; size: 12 }
  | { name: 'clipboard'; size: 16 }
  | { name: 'clipboard'; size: 24 }
  | { name: 'close'; size: 12 }
  | { name: 'close'; size: 16 }
  | { name: 'close'; size: 8 }
  | { name: 'cloud'; size: 16 }
  | { name: 'cloud'; size: 24 }
  | { name: 'compability'; size: 16 }
  | { name: 'compass'; size: 16 }
  | { name: 'compatibility'; size: 24 }
  | { name: 'contrast'; size: 16 }
  | { name: 'contrast'; size: 24 }
  | { name: 'copy'; size: 12 }
  | { name: 'cpu'; size: 16 }
  | { name: 'cpu'; size: 24 }
  | { name: 'delete'; size: 16 }
  | { name: 'delete'; size: 24 }
  | { name: 'disabled'; size: 12 }
  | { name: 'dislike'; size: 16 }
  | { name: 'dislike'; size: 24 }
  | { name: 'document'; size: 16 }
  | { name: 'document'; size: 24 }
  | { name: 'document-api'; size: 16 }
  | { name: 'dots'; size: 16 }
  | { name: 'dots'; size: 24 }
  | { name: 'download'; size: 24 }
  | { name: 'download-roundel'; size: 16 }
  | { name: 'edit'; size: 16 }
  | { name: 'email'; size: 16 }
  | { name: 'email'; size: 24 }
  | { name: 'error'; size: 12 }
  | { name: 'error'; size: 16 }
  | { name: 'error'; size: 24 }
  | { name: 'filter'; size: 12 }
  | { name: 'filter'; size: 16 }
  | { name: 'firewall'; size: 16 }
  | { name: 'firewall'; size: 24 }
  | { name: 'folder'; size: 16 }
  | { name: 'folder'; size: 24 }
  | { name: 'gateway'; size: 16 }
  | { name: 'gateway'; size: 24 }
  | { name: 'heart'; size: 16 }
  | { name: 'heart'; size: 24 }
  | { name: 'hide'; size: 12 }
  | { name: 'hide'; size: 16 }
  | { name: 'hide'; size: 24 }
  | { name: 'hourglass'; size: 16 }
  | { name: 'hourglass'; size: 24 }
  | { name: 'images'; size: 16 }
  | { name: 'images'; size: 24 }
  | { name: 'info'; size: 12 }
  | { name: 'info'; size: 16 }
  | { name: 'info'; size: 24 }
  | { name: 'instances'; size: 16 }
  | { name: 'instances'; size: 24 }
  | { name: 'integration'; size: 16 }
  | { name: 'ip-global'; size: 16 }
  | { name: 'ip-global'; size: 24 }
  | { name: 'ip-local'; size: 16 }
  | { name: 'ip-local'; size: 24 }
  | { name: 'issues'; size: 16 }
  | { name: 'issues'; size: 24 }
  | { name: 'key'; size: 12 }
  | { name: 'key'; size: 16 }
  | { name: 'key'; size: 24 }
  | { name: 'like'; size: 16 }
  | { name: 'like'; size: 24 }
  | { name: 'link'; size: 16 }
  | { name: 'load-balancer'; size: 16 }
  | { name: 'load-balancer'; size: 24 }
  | { name: 'loader'; size: 12 }
  | { name: 'location'; size: 24 }
  | { name: 'logs'; size: 16 }
  | { name: 'logs'; size: 24 }
  | { name: 'menu-close'; size: 12 }
  | { name: 'menu-open'; size: 12 }
  | { name: 'metrics'; size: 16 }
  | { name: 'metrics'; size: 24 }
  | { name: 'monitoring'; size: 16 }
  | { name: 'monitoring'; size: 24 }
  | { name: 'more'; size: 12 }
  | { name: 'networking'; size: 16 }
  | { name: 'networking'; size: 24 }
  | { name: 'new-window'; size: 16 }
  | { name: 'next-arrow'; size: 12 }
  | { name: 'notifications'; size: 16 }
  | { name: 'open-link'; size: 12 }
  | { name: 'organization'; size: 16 }
  | { name: 'organization'; size: 24 }
  | { name: 'overview'; size: 16 }
  | { name: 'overview'; size: 24 }
  | { name: 'person'; size: 16 }
  | { name: 'person'; size: 24 }
  | { name: 'person-group'; size: 16 }
  | { name: 'person-group'; size: 24 }
  | { name: 'prev-arrow'; size: 12 }
  | { name: 'profile'; size: 16 }
  | { name: 'progress'; size: 24 }
  | { name: 'prohibited'; size: 24 }
  | { name: 'question'; size: 12 }
  | { name: 'question'; size: 16 }
  | { name: 'question'; size: 24 }
  | { name: 'ram'; size: 16 }
  | { name: 'refresh'; size: 16 }
  | { name: 'repair'; size: 12 }
  | { name: 'repair'; size: 16 }
  | { name: 'resize'; size: 16 }
  | { name: 'resize'; size: 24 }
  | { name: 'router'; size: 16 }
  | { name: 'router'; size: 24 }
  | { name: 'safety'; size: 24 }
  | { name: 'search'; size: 16 }
  | { name: 'security'; size: 12 }
  | { name: 'security'; size: 16 }
  | { name: 'security'; size: 24 }
  | { name: 'select-arrows'; size: 6 }
  | { name: 'servers'; size: 16 }
  | { name: 'servers'; size: 24 }
  | { name: 'settings'; size: 16 }
  | { name: 'settings'; size: 24 }
  | { name: 'show'; size: 16 }
  | { name: 'sign-out'; size: 16 }
  | { name: 'snapshots'; size: 16 }
  | { name: 'snapshots'; size: 24 }
  | { name: 'software-update'; size: 16 }
  | { name: 'software-update'; size: 24 }
  | { name: 'sort'; size: 16 }
  | { name: 'sparkle'; size: 16 }
  | { name: 'speaker'; size: 24 }
  | { name: 'ssd'; size: 16 }
  | { name: 'storage'; size: 16 }
  | { name: 'storage'; size: 24 }
  | { name: 'submit'; size: 16 }
  | { name: 'subnet'; size: 16 }
  | { name: 'subnet'; size: 24 }
  | { name: 'success'; size: 12 }
  | { name: 'tags'; size: 16 }
  | { name: 'terminal'; size: 16 }
  | { name: 'terminal'; size: 24 }
  | { name: 'time'; size: 16 }
  | { name: 'transmit'; size: 16 }
  | { name: 'transmit'; size: 24 }
  | { name: 'unauthorized'; size: 12 }
  | { name: 'warning'; size: 12 }
  | { name: 'webhooks'; size: 16 }
  | { name: 'webhooks'; size: 24 }
  | { name: 'wireless'; size: 24 }
