name: Release

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened]

# Enabled permissions on GITHUB_TOKEN
permissions:
  # To be able to push to the repo
  contents: write
  # To update the pr description with canary info
  pull-requests: write
  # For pr-check to create a status
  statuses: write
  # Needed to create PR statuses/checks
  checks: write
  # To post comments on PRs
  issues: write
  # For trusted publishing
  id-token: write

jobs:
  validate-labels:
    runs-on: ubuntu-latest
    if:
      "!contains(github.event.head_commit.message, 'ci skip') &&
      !contains(github.event.head_commit.message, 'skip ci')"
    steps:
      - uses: actions/checkout@v5
      - run: git fetch --unshallow --tags
      - uses: actions/setup-node@v5
        with:
          node-version: 22.x
          cache: npm
      - run: npm install
      - name: Verify Release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run:
          npx auto pr-check
          --url=https://github.com/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID

  release:
    runs-on: ubuntu-latest
    environment: production
    if: |
      !contains(github.event.head_commit.message, 'ci skip') &&
      !contains(github.event.head_commit.message, 'skip ci')
    steps:
      - uses: actions/checkout@v5
        with:
          ref: ${{ github.head_ref || github.ref_name }}
      - run: git fetch --unshallow --tags
      - uses: actions/setup-node@v5
        with:
          node-version: 22.x
          cache: npm
      - run: npm install
      - run: npm install -g npm@latest

      - name: Build
        run: npm run build

      - name: Check theme changes
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add ./styles/dist
          if ! git diff --staged --quiet; then
            git commit -m "Update themes from token file"
            git push
          else
            echo "No theme changes detected. Continuing with release."
          fi

      - name: Create Release
        run: npm run release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
